import type { } from 'next'
// import { headers } from 'next/headers'

import { cookieToInitialState } from 'wagmi'

import { config } from './config'
import { ContextProvider } from './context'

export const metadata: any = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function Web3RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  // const initialState = cookieToInitialState(config, headers().get('cookie'))
  const initialState = cookieToInitialState(config,'')
  return (
    <html lang="en">
      <body>
        <ContextProvider 
          // initialState={initialState}
          initialState={initialState}
        >
          {children}
        </ContextProvider>
      </body>
    </html>
  )
}