export const assetData = [
  {
    icon: "/images/main/bit.png",
    title: "Bitcoin",
    initial: "BTC",
    price: "$28,000",
    profit: "+2.5%",
    balance: "0",
    value: "$0.00",
  },
  {
    icon: "/images/main/bit.png",
    title: "Bitcoin",
    initial: "BTC",
    price: "$28,000",
    profit: "+2.5%",
    balance: "0",
    value: "$0.00",
  },
  {
    icon: "/images/main/bit.png",
    title: "Bitcoin",
    initial: "BTC",
    price: "$28,000",
    profit: "+2.5%",
    balance: "0",
    value: "$0.00",
  },
  {
    icon: "/images/main/tet.png",
    title: "USDT",
    initial: "USDT",
    price: "$28,000",
    profit: "+2.5%",
    balance: "0",
    value: "$0.00",
  },
  {
    icon: "/images/main/bit.png",
    title: "Bitcoin",
    initial: "BTC",
    price: "$28,000",
    profit: "+2.5%",
    balance: "0",
    value: "$0.00",
  },
  {
    icon: "/images/main/tet.png",
    title: "USDT",
    initial: "USDT",
    price: "$28,000",
    profit: "+2.5%",
    balance: "0",
    value: "$0.00",
  },
]